### ISSUE TITLE
[FEATURE]How to configure https？

### ISSUE THREAD

**Issue by qhtml5** [sprintcube/docker-compose-lamp#196] opened 2022-05-06 15:32 UTC
https how to configure certs location settings

**Comment by alainseys** [comment] 2022-05-22 10:03
@qhtml5 here should be the first step a good implementation to handle the dns request properly without any /etc/hosts adjustments here we can take a look at dnsmasq when this is implemented correctly you can create ssl certificates properly (without any ssl warnings)

**Comment by MrOffline77** [comment] 2022-05-22 11:17
Hi all, 
thank your for your contribution to this project. 
I would like to discuss with you if the SSL termination is in scope for the project. 
The project serves as a local development environment. The question is to what extent the SSL termination is necessary here. To encrypt traffic ? To secure communication - if yes against what ? 
Could you @qhtml5  explain us your usecase a little bit more, so we can better understand your issue in this case  ? 
In general, you can modify SSL Locations inside the Apache Webserver configuration. 
Thank you !

**Comment by alainseys** [comment] 2022-05-22 11:47
@MrOffline77 in my opinion a local dev en should be as close to an production environment so you can test you applications with ask enabled

**Comment by alainseys** [comment] 2022-05-29 19:12
Hi, @MrOffline77 

since i dit not received any feedback i have made an implementation of this that is workable

with dnsmasq active your local system wil listen on the *.test TLD without any need of changing /etc/hosts

<img width="772" alt="Screenshot 2022-05-29 at 21 11 12" src="https://user-images.githubusercontent.com/19891785/170887593-4723c630-8430-4e1e-a7e9-9d1f67eff941.png">

**Comment by blizzardengle** [comment] 2022-06-29 17:40
> To secure communication - if yes against what ? ( @MrOffline77 )

For me I do a lot of API integrations for work and when testing integrations I can use `localhost` only if it has been secured: `https://localhost`. I also agree with:

> A local dev [environment] should be as close to [a] production environment [as possible] ( @alainseys )

I found that this desire has been around for a while in #40 and #68 but it appears it has been abandoned. I plan to modify my local LAMP stack (built with this repo) using, [Setup an Apache, PHP, and HTTPS development environment with Docker](https://dockerwebdev.com/tutorials/docker-php-development/), for now.

I think it would be a great addition to have this feature built-in to the LAMP stack.

**Comment by alainseys** [comment] 2022-06-29 21:35
@blizzardengle  to implement https good you can take a look at dnsmask this will allow you to use a TLD like yourapplication.test with this implemented you can easy integrate https to your project

**Comment by blizzardengle** [comment] 2022-06-29 22:26
@alainseys thank you for the suggestion. I followed [Setup an Apache, PHP, and HTTPS development environment with Docker](https://dockerwebdev.com/tutorials/docker-php-development/) (with several modifications) and got `https` on `localhost` working.

I personally prefer this method because adding a new TLD like `yourapplication.test` is as simple as adding `yourapplication.test` to your computers host file and then adding a new entry in the `config/vhosts/default.conf` file. So almost everything SSL related is tied to your LAMP (docker) setup, except for editing your local host file.

I'll post a new comment here soon with a link to a PR that adds this feature to sprintcube's `docker-compose-lamp`.

**Comment by blizzardengle** [comment] 2022-06-30 16:37
@alainseys just created the PR, see above comment. Since there is a little configuration involved here is a copy of the PR message:

<hr>

This PR ( #208 ) adds support for SSL (HTTPS) in the LAMP server. It was designed to add simple `https` support on `localhost` but can be used for any domain name. 

### HTTPS on Localhost
To use `https://localhost` you will need to:
1. Use a tool like [mkcert](https://github.com/FiloSottile/mkcert#installation) to create an SSL certificate for `localhost`.
    - With `mkcert`, in the terminal run `mkcert localhost 127.0.0.1 ::1`
    - Rename the files `cert.pem` and `cert-key.pem` respectively
    - Move the files into your docker setup by placing them in `config/ssl`
2. You will need to uncomment the `443` vhost in `config/vhosts/default.conf`

### HTTPS with any Domain
1. Follow step 1 from the previous section `HTTPS on Localhost` but for the domain you wish to use locally.
    - You should probably choose different names for the files cert.pem` and `cert-key.pem`, especially if you plan to add several `https` protected domains.
2. You will need to edit you machines `hosts` file and point the domain(s) to `127.0.0.1`; these domains are meant for testing locally, we don't want your computer to perform a DNS query searching the internet for the domain.
3. You will need to uncomment the `443` vhost in `config/vhosts/default.conf` and modify it to match your domain name and certificate file names.
    - If you have multiple domains on `https (443)` then you will need to create multiple vhost entries for each of those domains.

### Notable Additions by this PR
- Adds an `ssl` folder under `config` for your ssl cert(s)
- Adds the environment variable `SSL_DIR` that points to `./config/ssl`
- Adds the environment variable `HOST_MACHINE_PMA_SECURE_PORT` to hopefully allow `https` access to `phpmyadmin`
    - Currently not working. I could use help with this if anyone is interested.
- Adds this line under `volumes` for the `webserver` in the `docker-compose` file: `- ${SSL_DIR-./config/ssl}:/etc/apache2/ssl/`
    - This is what allows you to place ssl certs in `config/ssl` and have them auto load into the server on startup. 
-  Adds this line under `ports` for the `phpmyadmin` in the `docker-compose` file: `- "${HOST_MACHINE_PMA_SECURE_PORT}:443"`
    - Currently not working. I could use help with this if anyone is interested.

**Comment by MrOffline77** [comment] 2022-07-06 17:28
@blizzardengle 
Thank you for great explanations. Sound totally reasonable to me. 
Since I now know the use case better and it looks like there is a real usecase even inside dev envs, I merged you pull #208. 
Thank you very much for your contribution. Feel free to create pull or issues for other stuff you think is missing :).
Cheers

**Closed by MrOffline77** 2022-07-06 17:28 UTC
