### ISSUE TITLE
[BUG] Can not connect to PHPMyAdmin

### ISSUE THREAD

**Issue by crscaballero** [sprintcube/docker-compose-lamp#108] opened 2020-04-01 03:13 UTC
**Describe the bug**
Getting error on PHP My Admin, 

**which Branch / PHP Version are you using ?**
7.4.x

**To Reproduce**
1. Git Clone
2. Checkout to 7.4.x
3. Copy `sample.env` to `.env` file
4. Go to `http://localhost:8080/`

**Expected behavior**
Go to manage PHPMyAdmin

**Screenshots**
![image](https://user-images.githubusercontent.com/48134692/78095429-c6223380-738b-11ea-83de-ba15703f9be4.png)

**Desktop (please complete the following information):**
 - OS: Windoes 10
 - Browser Mozilla Firefoz and Google Chrome, same behavior on both
 - Docker Version: 19.03.8

**Additional context**
No additional context, just thanks in advance for the help

**Comment by MrOffline77** [comment] 2020-04-01 10:38
Hi,
I would bet, that you mysql container is not running or doing weird things. 
Can you check this und send the `docker logs <containeruuid>`here ?

**Comment by crscaballero** [comment] 2020-04-02 02:14
Here is the log

![image](https://user-images.githubusercontent.com/48134692/78203881-fe3d7b00-744c-11ea-9a03-3c2c47139347.png)

thanks in advance

**Comment by MrOffline77** [comment] 2020-04-11 19:27
Thats strange. Sounds somehow like your .env is modified somehow and the mysql logins aren't correct. The Error indicates, that the connection over docker network to the mysql works, and mysql reponds with a valid error for incorrect credentials. Can you double check that your credentials the same like in our provided env files ?

**Comment by crscaballero** [comment] 2020-04-11 19:35
DOCUMENT_ROOT=./www
      VHOSTS_DIR=./config/vhosts
      APACHE_LOG_DIR=./logs/apache2
      PHP_INI=./config/php/php.ini
      
      # If you want to use mariadb instead of mysql use "mariadb"
      DATABASE=mysql8
      
      MYSQL_DATA_DIR=./data/mysql
      MYSQL_LOG_DIR=./logs/mysql
      
      # If you already has the port 80 in use, you can change it (for example if you have Apache)
      HOST_MACHINE_UNSECURE_HOST_PORT=80
      HOST_MACHINE_SECURE_HOST_PORT=443
      
      # If you already has the port 3306 in use, you can change it (for example if you have MySQL)
      HOST_MACHINE_MYSQL_PORT=3306
      
      # If you already has the port 6379 in use, you can change it (for example if you have Redis)
      HOST_MACHINE_REDIS_PORT=6379
      
      
      # MySQL root user password
      MYSQL_ROOT_PASSWORD=tiger
      
      # Database settings: Username, password and database name
      MYSQL_USER=docker
      MYSQL_PASSWORD=docker
      MYSQL_DATABASE=docker


This is my `.env` file, exactly same than `sample.env` and my MySQL data is empty

**Comment by MrOffline77** [comment] 2020-04-11 20:01
I've just spun up a fresh 7.4.x stack, but im not able to reproduce this.
Can you verify that you can't login manual ? 
Just to make sure, please git pull, to make sure your branch is up-to-date

Please give this a try and let me know what the results are. 
```
docker exec -ti 7.4.x-webserver bash
mysql -h mysql -uroot -ptiger
or 
mysql -h mysql -udocker -pdocker
```

**Comment by crscaballero** [comment] 2020-04-11 21:03
I did, and works, so then I've change the params in the `.env` file

      # Database settings: Username, password and database name
      MYSQL_USER=root
      MYSQL_PASSWORD=tiger
      MYSQL_DATABASE=

and with this is working as supposed to be, I think the `sample.env` should be have those values instead of the current values, are you agree if I send a PR with that small change?

**Comment by nathanielkam** [comment] 2020-06-27 03:14
Experiencing the same issue on php 7.3 branch. Will submit a PR for them shortly. 

@crscaballero 's fix worked for me.

**Comment by nathanielkam** [comment] 2020-06-27 03:21
Sorry didn't commit that with the best message, but here is the fix.  https://github.com/sprintcube/docker-compose-lamp/pull/132

**Comment by MrOffline77** [comment] 2020-10-03 11:36
@nathanielkam Can you confirm that this is fixed with the latest commit ?

**Closed** 2021-09-25 13:02 UTC
