### ISSUE TITLE
[BUG] MySQL connect failed  to install spip

### ISSUE THREAD

**Issue by benoitldr** [sprintcube/docker-compose-lamp#216] opened 2022-10-16 21:12 UTC
**Describe the bug**
I cannot connect to database to install [spip](https://www.spip.net/en_rubrique25.html)
I have this two tests working
Test DB Connection with mysqli
Test DB Connection with PDO

**which Branch / PHP Version are you using ?**
php74
mariadb105
other config in .env is by dafault

1. `mkdir www/spip`
2. `cd www/spip`
3. `wget https://get.spip.net/spip_loader.php .`
4. `chown user:user -R ./www/spip`
5. go to http://localhost/spip/spip_loader.php
6. etape 1 with 
- databse adresse : locahost or localhost:3306
- login : root or docker
- password : tiger or docker

**Expected behavior**
I should manage to connect to mysql database via spip installation, phpmyadmin acess http://localhost:8080 & test from index working

**Screenshots**
![spip-error-database](https://user-images.githubusercontent.com/17094722/196058302-7c045fa6-fe04-472f-8ced-df1b23a96005.png)
![spip-error_000](https://user-images.githubusercontent.com/17094722/196058508-53c4c51b-710e-45ab-8910-112fad60f95b.png)

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser firefox or librewolf
 - Docker Version: Docker version 20.10.19, build d85ef84533
```
docker -v
Docker version 20.10.19, build d85ef84533
```
** Additional information
`sudo docker-compose exec webserver bash`
`mariadb`
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by tarlepp** [comment] 2022-10-17 19:17
Should this issue marked as closed - because it's look like the issue is solved?

**Closed** 2022-12-18 18:56 UTC
